### ISSUE TITLE
The following NotInitializedError was thrown attaching to the render tree: Instance of 'NotInitializedError'

### ISSUE THREAD

**Issue by maverickasdev** [viktorvoltz/SAND-wallet#1]
I got this issue when running the project. Do you know how to fix it?

**Comment by viktorvoltz** [comment]
Thank you for feedback I'll look at it now

**Comment by viktorvoltz** [comment]
@ThuyenPV I need more information on how you got this error. Also, did you compile and migrate the smart contracts to Ganache before running the project?
